### ISSUE TITLE
New Relic provider panics, crashes Terraform, when RPC errors encountered

### ISSUE THREAD

**Issue by tomdeering-wf** [newrelic/terraform-provider-newrelic#1173]
`terraform plan` crashes when the new relic provider panics. The stack trace looks like RPC errors from the New Relic One APIs are not properly handled, then a `nil` object is type-asserted in an unsafe way.
```
panic: interface conversion: entities.EntityInterface is nil, not *entities.DashboardEntity
```

### Terraform Version
```
Terraform v0.14.6
+ provider registry.terraform.io/hashicorp/aws v3.26.0
+ provider registry.terraform.io/newrelic/newrelic v2.17.0
```

### Affected Resource(s)
- `newrelic_alert_channel`
- `newrelic_alert_policy`
- `newrelic_alert_policy_channel`
- `newrelic_nrql_alert_condition`
- `newrelic_one_dashboard`

This looks like a general bug with the provider, rather than with a particular resource.

### Terraform Configuration
```hcl
variable "region" { default = <redacted>  }

variable "account_id" { default = <redacted> }

data "aws_secretsmanager_secret" "new_relic_api_keys_secret" {
  arn = <redacted>
}

data "aws_secretsmanager_secret_version" "new_relic_api_keys_secret_version" {
  secret_id = data.aws_secretsmanager_secret.new_relic_api_keys_secret.id
}

provider "newrelic" {
  api_key       = jsondecode(data.aws_secretsmanager_secret_version.new_relic_api_keys_secret_version.secret_string)["api_key"]
  admin_api_key = jsondecode(data.aws_secretsmanager_secret_version.new_relic_api_keys_secret_version.secret_string)["admin_api_key"]

  account_id = var.account_id
  region     = "US"
}

provider "aws" { region = var.region }

terraform {
  backend "s3" {
    bucket = <redacted>
    key    = <redacted>
    region = <redacted>
  }
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.6"
    }
    newrelic = {
      source  = "newrelic/newrelic"
      version = "~> 2.17"
    }
  }
}

module "dashboards" {
  source = "./dashboards"
}

module "alerts" {
  source = "./alerts"
}
```

### Actual Behavior
New Relic provider panicked and crashed Terraform.

### Expected Behavior
New Relic provider returns API error in an orderly way back to Terraform. 

### Steps to Reproduce
1. `terraform plan`

### Debug Output
[cli output](https://gist.github.com/tomdeering-wf/bb4b35859444c71b4fcab4ee01cc9abc)

### Panic Output
[crash.log](https://gist.github.com/tomdeering-wf/e3a54d3f2442a7041da616e818930156)

### Important Factoids
We previously had no problems with `terraform plan` for our resources. Issues started today when the New Relic One APIs seemingly had issues.

**Comment by tomdeering-wf** [comment]
Possibly related to https://github.com/newrelic/terraform-provider-newrelic/issues/1171

**Comment by rizalgowandy** [comment]
I am also facing this issue since yesterday.
Basically, somehow the connection between Terraform Cloud and NewRelic is somehow broken
and we cannot get the dashboard entity, and the plugin code doesn't handle the conversion of the nil type.

```
Terraform v0.14.5
Configuring remote state backend...
Initializing Terraform configuration...
[0m[1mnewrelic_alert_channel.pagerduty_notification: Refreshing state... [id=4771298][0m
[0m[1mnewrelic_alert_channel.email_notification: Refreshing state... [id=4771300][0m
[0m[1mnewrelic_alert_policy.golden_signal_policy: Refreshing state... [id=1227630][0m
[0m[1mmodule.nsq.newrelic_one_dashboard.main: Refreshing state... [id=MjkwNTcwOHxWSVp8REFTSEJPQVJEfDE2OTIzMTA][0m
[0m[1mnewrelic_alert_channel.slack_notification: Refreshing state... [id=4771299][0m
[0m[1mmodule.grpc.newrelic_one_dashboard.main: Refreshing state... [id=MjkwNTcwOHxWSVp8REFTSEJPQVJEfDE2OTIzMDk][0m
[31m
[1m[31mError: [0m[0m[1mrpc error: code = Unavailable desc = transport is closing[0m

[0m[0m[0m
[31m
[1m[31mError: [0m[0m[1mrpc error: code = Unavailable desc = transport is closing[0m

[0m[0m[0m
[31m
[1m[31mError: [0m[0m[1mrpc error: code = Unavailable desc = transport is closing[0m

[0m[0m[0m
[31m
[1m[31mError: [0m[0m[1mrpc error: code = Unavailable desc = transport is closing[0m

[0m[0m[0m
[31m
[1m[31mError: [0m[0m[1mrpc error: code = Unavailable desc = transport is closing[0m

[0m[0m[0m
[31m
[1m[31mError: [0m[0m[1mrpc error: code = Unavailable desc = transport is closing[0m

[0m[0m[0m
[31m
[1m[31mError: [0m[0m[1mrpc error: code = Unavailable desc = transport is closing[0m

[0m[0m[0m
panic: interface conversion: entities.EntityInterface is nil, not *entities.DashboardEntity
2021-02-12T08:35:25.737Z [DEBUG] plugin.terraform-provider-newrelic_v2.18.0: 
2021-02-12T08:35:25.737Z [DEBUG] plugin.terraform-provider-newrelic_v2.18.0: goroutine 50 [running]:
2021-02-12T08:35:25.737Z [DEBUG] plugin.terraform-provider-newrelic_v2.18.0: github.com/newrelic/newrelic-client-go/pkg/dashboards.(*Dashboards).GetDashboardEntity(0xc00039e898, 0xc000649680, 0x27, 0x1, 0x1, 0x13080a0)
2021-02-12T08:35:25.737Z [DEBUG] plugin.terraform-provider-newrelic_v2.18.0: 	/home/runner/go/pkg/mod/github.com/newrelic/newrelic-client-go@v0.57.2/pkg/dashboards/dashboard.go:61 +0x1c1
2021-02-12T08:35:25.737Z [DEBUG] plugin.terraform-provider-newrelic_v2.18.0: github.com/newrelic/terraform-provider-newrelic/v2/newrelic.resourceNewRelicOneDashboardRead(0xc0002938f0, 0x116d000, 0xc00067f140, 0xc0002938f0, 0x0)
2021-02-12T08:35:25.737Z [DEBUG] plugin.terraform-provider-newrelic_v2.18.0: 	/home/runner/work/terraform-provider-newrelic/terraform-provider-newrelic/newrelic/resource_newrelic_one_dashboard.go:344 +0x154
2021-02-12T08:35:25.737Z [DEBUG] plugin.terraform-provider-newrelic_v2.18.0: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0004d3200, 0xc0002825f0, 0x116d000, 0xc00067f140, 0xc00000e410, 0x0, 0x0)
2021-02-12T08:35:25.737Z [DEBUG] plugin.terraform-provider-newrelic_v2.18.0: 	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.16.0/helper/schema/resource.go:460 +0x119
2021-02-12T08:35:25.737Z [DEBUG] plugin.terraform-provider-newrelic_v2.18.0: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0xc00009b1b8, 0x1621d80, 0xc0008578c0, 0xc000070900, 0xc00009b1b8, 0xc0008578c0, 0xc0005e9ba0)
2021-02-12T08:35:25.737Z [DEBUG] plugin.terraform-provider-newrelic_v2.18.0: 	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.16.0/internal/helper/plugin/grpc_provider.go:525 +0x3d8
2021-02-12T08:35:25.737Z [DEBUG] plugin.terraform-provider-newrelic_v2.18.0: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadResource_Handler(0x12f58a0, 0xc00009b1b8, 0x1621d80, 0xc0008578c0, 0xc000070840, 0x0, 0x1621d80, 0xc0008578c0, 0xc000868000, 0x102b)
2021-02-12T08:35:25.737Z [DEBUG] plugin.terraform-provider-newrelic_v2.18.0: 	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.16.0/internal/tfplugin5/tfplugin5.pb.go:3269 +0x217
2021-02-12T08:35:25.737Z [DEBUG] plugin.terraform-provider-newrelic_v2.18.0: google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001b2e00, 0x162fb20, 0xc000001980, 0xc0003bb100, 0xc0001ac4e0, 0x1f3bf70, 0x0, 0x0, 0x0)
2021-02-12T08:35:25.737Z [DEBUG] plugin.terraform-provider-newrelic_v2.18.0: 	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.30.0/server.go:1171 +0x50a
2021-02-12T08:35:25.737Z [DEBUG] plugin.terraform-provider-newrelic_v2.18.0: google.golang.org/grpc.(*Server).handleStream(0xc0001b2e00, 0x162fb20, 0xc000001980, 0xc0003bb100, 0x0)
2021-02-12T08:35:25.737Z [DEBUG] plugin.terraform-provider-newrelic_v2.18.0: 	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.30.0/server.go:1494 +0xccd
2021-02-12T08:35:25.737Z [DEBUG] plugin.terraform-provider-newrelic_v2.18.0: google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000098410, 0xc0001b2e00, 0x162fb20, 0xc000001980, 0xc0003bb100)
2021-02-12T08:35:25.737Z [DEBUG] plugin.terraform-provider-newrelic_v2.18.0: 	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.30.0/server.go:834 +0xa1
2021-02-12T08:35:25.737Z [DEBUG] plugin.terraform-provider-newrelic_v2.18.0: created by google.golang.org/grpc.(*Server).serveStreams.func1
2021-02-12T08:35:25.737Z [DEBUG] plugin.terraform-provider-newrelic_v2.18.0: 	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.30.0/server.go:832 +0x204
2021/02/12 08:35:25 [TRACE] vertex "module.grpc.newrelic_one_dashboard.main": visit complete
2021/02/12 08:35:25 [TRACE] vertex "module.grpc.newrelic_one_dashboard.main": dynamic subgraph encountered errors
2021/02/12 08:35:25 [TRACE] vertex "module.grpc.newrelic_one_dashboard.main": visit complete
2021/02/12 08:35:25 [TRACE] vertex "module.grpc.newrelic_one_dashboard.main (expand)": dynamic subgraph encountered errors
2021/02/12 08:35:25 [TRACE] vertex "module.grpc.newrelic_one_dashboard.main (expand)": visit complete
2021/02/12 08:35:25 [TRACE] dag/walk: upstream of "module.grpc.output.dashboard_url (expand)" errored, so skipping
2021/02/12 08:35:25 [TRACE] dag/walk: upstream of "output.grpc_dashboard_url" errored, so skipping
2021/02/12 08:35:25 [TRACE] vertex "newrelic_alert_channel.slack_notification": visit complete
2021/02/12 08:35:25 [TRACE] vertex "newrelic_alert_channel.slack_notification": dynamic subgraph encountered errors
2021/02/12 08:35:25 [TRACE] vertex "newrelic_alert_channel.slack_notification": visit complete
2021/02/12 08:35:25 [TRACE] vertex "newrelic_alert_channel.slack_notification (expand)": dynamic subgraph encountered errors
2021/02/12 08:35:25 [TRACE] vertex "newrelic_alert_channel.slack_notification (expand)": visit complete
2021/02/12 08:35:25 [TRACE] vertex "newrelic_alert_policy.golden_signal_policy": visit complete
2021/02/12 08:35:25 [TRACE] vertex "newrelic_alert_policy.golden_signal_policy": dynamic subgraph encountered errors
2021/02/12 08:35:25 [TRACE] vertex "newrelic_alert_policy.golden_signal_policy": visit complete
2021/02/12 08:35:25 [TRACE] vertex "newrelic_alert_policy.golden_signal_policy (expand)": dynamic subgraph encountered errors
2021/02/12 08:35:25 [TRACE] vertex "newrelic_alert_policy.golden_signal_policy (expand)": visit complete
2021-02-12T08:35:25.738Z [DEBUG] plugin: plugin process exited: path=.terraform/providers/registry.terraform.io/newrelic/newrelic/2.18.0/linux_amd64/terraform-provider-newrelic_v2.18.0 pid=1611 error="exit status 2"
2021-02-12T08:35:25.739Z [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2021/02/12 08:35:25 [TRACE] vertex "newrelic_alert_channel.email_notification": visit complete
2021/02/12 08:35:25 [TRACE] vertex "newrelic_alert_channel.email_notification": dynamic subgraph encountered errors
2021/02/12 08:35:25 [TRACE] vertex "newrelic_alert_channel.email_notification": visit complete
2021/02/12 08:35:25 [TRACE] vertex "newrelic_alert_channel.email_notification (expand)": dynamic subgraph encountered errors
2021/02/12 08:35:25 [TRACE] vertex "newrelic_alert_channel.email_notification (expand)": visit complete
2021/02/12 08:35:25 [TRACE] dag/walk: upstream of "newrelic_alert_muting_rule.midnight (expand)" errored, so skipping
2021/02/12 08:35:25 [TRACE] vertex "newrelic_alert_channel.pagerduty_notification": visit complete
2021/02/12 08:35:25 [TRACE] vertex "newrelic_alert_channel.pagerduty_notification": dynamic subgraph encountered errors
2021/02/12 08:35:25 [TRACE] vertex "newrelic_alert_channel.pagerduty_notification": visit complete
2021/02/12 08:35:25 [TRACE] vertex "newrelic_alert_channel.pagerduty_notification (expand)": dynamic subgraph encountered errors
2021/02/12 08:35:25 [TRACE] vertex "newrelic_alert_channel.pagerduty_notification (expand)": visit complete
2021/02/12 08:35:25 [TRACE] dag/walk: upstream of "newrelic_alert_policy_channel.alert_channels (expand)" errored, so skipping
2021/02/12 08:35:25 [TRACE] vertex "module.nsq.newrelic_one_dashboard.main": visit complete
2021/02/12 08:35:25 [TRACE] vertex "module.nsq.newrelic_one_dashboard.main": dynamic subgraph encountered errors
2021/02/12 08:35:25 [TRACE] vertex "module.nsq.newrelic_one_dashboard.main": visit complete
2021/02/12 08:35:25 [TRACE] vertex "module.nsq.newrelic_one_dashboard.main (expand)": dynamic subgraph encountered errors
2021/02/12 08:35:25 [TRACE] vertex "module.nsq.newrelic_one_dashboard.main (expand)": visit complete
2021/02/12 08:35:25 [TRACE] dag/walk: upstream of "module.nsq.output.dashboard_url (expand)" errored, so skipping
2021/02/12 08:35:25 [TRACE] dag/walk: upstream of "output.nsq_dashboard_url" errored, so skipping
2021/02/12 08:35:25 [TRACE] vertex "data.newrelic_entity.grpc": visit complete
2021/02/12 08:35:25 [TRACE] vertex "data.newrelic_entity.grpc": dynamic subgraph encountered errors
2021/02/12 08:35:25 [TRACE] vertex "data.newrelic_entity.grpc": visit complete
2021/02/12 08:35:25 [TRACE] vertex "data.newrelic_entity.grpc (expand)": dynamic subgraph encountered errors
2021/02/12 08:35:25 [TRACE] vertex "data.newrelic_entity.grpc (expand)": visit complete
2021/02/12 08:35:25 [TRACE] dag/walk: upstream of "newrelic_infra_alert_condition.host_not_reporting (expand)" errored, so skipping
2021/02/12 08:35:25 [TRACE] dag/walk: upstream of "newrelic_alert_condition.throughput_web (expand)" errored, so skipping
2021/02/12 08:35:25 [TRACE] dag/walk: upstream of "newrelic_infra_alert_condition.high_cpu (expand)" errored, so skipping
2021/02/12 08:35:25 [TRACE] dag/walk: upstream of "newrelic_infra_alert_condition.high_disk_usage (expand)" errored, so skipping
2021/02/12 08:35:25 [TRACE] dag/walk: upstream of "newrelic_alert_condition.response_time_web (expand)" errored, so skipping
2021/02/12 08:35:25 [TRACE] dag/walk: upstream of "module.nsq.var.application_id (expand)" errored, so skipping
2021/02/12 08:35:25 [TRACE] dag/walk: upstream of "module.nsq (close)" errored, so skipping
2021/02/12 08:35:25 [TRACE] dag/walk: upstream of "newrelic_entity_tags.tags (expand)" errored, so skipping
2021/02/12 08:35:25 [TRACE] dag/walk: upstream of "module.grpc.var.application_id (expand)" errored, so skipping
2021/02/12 08:35:25 [TRACE] dag/walk: upstream of "module.grpc (close)" errored, so skipping
2021/02/12 08:35:25 [TRACE] dag/walk: upstream of "newrelic_alert_condition.error_percentage (expand)" errored, so skipping
2021/02/12 08:35:25 [TRACE] dag/walk: upstream of "provider[\"registry.terraform.io/newrelic/newrelic\"] (close)" errored, so skipping
2021/02/12 08:35:25 [TRACE] dag/walk: upstream of "meta.count-boundary (EachMode fixup)" errored, so skipping
2021/02/12 08:35:25 [TRACE] dag/walk: upstream of "root" errored, so skipping
2021/02/12 08:35:25 [INFO] backend/local: plan operation completed
2021-02-12T08:35:25.740Z [DEBUG] plugin: plugin exited



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.log" file that was created may contain 
sensitive information that must be redacted before it is safe to share 
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

```

**Comment by crisrise** [comment]
I am experiencing a very similar issue as well with provider v2.18.0

**Comment by jthurman42** [comment]
Tracing this back, looks like related to the issue here: newrelic/newrelic-client-go#684 If a dashboard was fetched, but did not return, then there was a panic for nil interface conversion.

**Comment by sanderblue** [comment]
Did the **v2.19.1** release resolve this?

**Comment by t-jithinkrishna** [comment]
Is the version - v2.19.1 released ?

**Comment by jthurman42** [comment]
@t-jithinkrishna Build pipeline was jammed up, so v2.19.1 was released slightly after the ask (instead of before as anticipated).  v2.20.0 shipped today.  Please verify if you're still having the same issue.  Thanks!

**Comment by crisrise** [comment]
The crash I was experiencing with newrelic_one_dashbard in v2.18.0 is not there any more with v2.20.0. From my point of view it is solved, thanks!
