### ISSUE TITLE
Plugin error due to GRPCProvider

### ISSUE THREAD

**Issue by rdhar** [newrelic/terraform-provider-newrelic#1525]
Upon applying an existing plan with no changes, the following error is returned:

```bash
│ Error: Plugin did not respond
│
│   with module.pl032__alerts.newrelic_nrql_alert_condition.multi__condition["static_latency_service_database"],
│   on modules\alerts\main.tf line 7, in resource "newrelic_nrql_alert_condition" "multi__condition":
│    7: resource "newrelic_nrql_alert_condition" "multi__condition" {
│
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain 
│ more details.
```

<details><summary>View entire stack trace from plugin crash error log:</summary>

```bash
╷
│ Error: Plugin did not respond
│
│   with module.pl032__alerts.newrelic_nrql_alert_condition.multi__condition["static_latency_service_database"],
│   on modules\alerts\main.tf line 7, in resource "newrelic_nrql_alert_condition" "multi__condition":
│    7: resource "newrelic_nrql_alert_condition" "multi__condition" {
│
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain
│ more details.
╵

Stack trace from the terraform-provider-newrelic_v2.31.1.exe plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0xa0 pc=0x12e7333]

goroutine 89 [running]:
github.com/newrelic/terraform-provider-newrelic/v2/newrelic.resourceNewRelicNrqlAlertConditionCreate(0x17bb9f8, 0xc0000d46c0, 0xc00013e480, 0x1421ae0, 0xc000281b30, 0xc000250970, 0xec1cb2, 0xc00013e280)
        /home/runner/work/terraform-provider-newrelic/terraform-provider-newrelic/newrelic/resource_newrelic_nrql_alert_condition.go:432 +0x7d3
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc0008327e0, 0x17bb988, 0xc000428340, 0xc00013e480, 0x1421ae0, 0xc000281b30, 0x0, 0x0, 0x0)
        /home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.8.0/helper/schema/resource.go:330 +0x187
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0008327e0, 0x17bb988, 0xc000428340, 0xc00024c5b0, 0xc00013e280, 0x1421ae0, 0xc000281b30, 0x0, 0x0, 0x0, ...)
        /home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.8.0/helper/schema/resource.go:456 +0x67b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0007ac108, 0x17bb988, 0xc000428340, 0xc000074820, 0xc000428340, 0x153ea40, 0xc0002ea100)
        /home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.8.0/helper/schema/grpc_provider.go:977 +0xacf
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0000f5a40, 0x17bba30, 0xc000428340, 0xc0003e6070, 0xc0000f5a40,
0xc0002ea180, 0xc0006dfba0)
        /home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.4.0/tfprotov5/tf5server/server.go:332 +0xb6
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x153ea40, 0xc0000f5a40, 0x17bba30, 0xc0002ea180,
0xc0000d41e0, 0x0, 0x17bba30, 0xc0002ea180, 0xc0006e8c00, 0xaca)
        /home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.4.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x222
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00032c540, 0x17c61f8, 0xc0004c0d80, 0xc0006d2000, 0xc00018ce40, 0x1de43c0, 0x0, 0x0, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc00032c540, 0x17c61f8, 0xc0004c0d80, 0xc0006d2000, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0002961e0, 0xc00032c540, 0x17c61f8, 0xc0004c0d80, 0xc0006d2000)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:859 +0xb2
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0xa0 pc=0x12e7333]

goroutine 120 [running]:
github.com/newrelic/terraform-provider-newrelic/v2/newrelic.resourceNewRelicNrqlAlertConditionCreate(0x17bb9f8, 0xc00066c7e0, 0xc00030e380, 0x1421ae0, 0xc0006a5cb0, 0xc0005452e0, 0xec1cb2, 0xc00030e200)
        /home/runner/work/terraform-provider-newrelic/terraform-provider-newrelic/newrelic/resource_newrelic_nrql_alert_condition.go:432 +0x7d3
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc000256d20, 0x17bb988, 0xc000b04100, 0xc00030e380, 0x1421ae0, 0xc0006a5cb0, 0x0, 0x0, 0x0)
        /home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.8.0/helper/schema/resource.go:330 +0x187
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000256d20, 0x17bb988, 0xc000b04100, 0xc00009d5f0, 0xc00030e200, 0x1421ae0, 0xc0006a5cb0, 0x0, 0x0, 0x0, ...)
        /home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.8.0/helper/schema/resource.go:456 +0x67b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0000987b0, 0x17bb988, 0xc000b04100, 0xc0003cc0a0, 0xc000b04100, 0x153ea40, 0xc0007fef00)
        /home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.8.0/helper/schema/grpc_provider.go:977 +0xacf
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0006633e0, 0x17bba30, 0xc000b04100, 0xc0003da0e0, 0xc0006633e0,
0xc0007fefc0, 0xc000807ba0)
        /home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.4.0/tfprotov5/tf5server/server.go:332 +0xb6
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x153ea40, 0xc0006633e0, 0x17bba30, 0xc0007fefc0,
0xc00066c120, 0x0, 0x17bba30, 0xc0007fefc0, 0xc00041c400, 0xaca)
        /home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.4.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x222
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000b6540, 0x17c61f8, 0xc000292300, 0xc0000fe100, 0xc00068e510, 0x1de43c0, 0x0, 0x0, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc0000b6540, 0x17c61f8, 0xc000292300, 0xc0000fe100, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0000322b0, 0xc0000b6540, 0x17c61f8, 0xc000292300, 0xc0000fe100)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:859 +0xb2
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd

Error: The terraform-provider-newrelic_v2.31.1.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
╷
│ Error: Plugin did not respond
│
│   with module.pl023__alerts.newrelic_nrql_alert_condition.multi__condition["static_latency_service_database"],
│   on modules\alerts\main.tf line 7, in resource "newrelic_nrql_alert_condition" "multi__condition":
│    7: resource "newrelic_nrql_alert_condition" "multi__condition" {
│
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain
│ more details.
╵
```
</details>

I'm running Terraform v1.0.10 with newrelic prpovider v2.31.1 on Windows 10 x64. Happy to share more info if requested.

Thanks for your time,
Rishav

**Comment by pmoranga** [comment]
@rdhar from time to time I get Terraform issues after adding the New Relic provider to my project. Before that using just AWS provider it was solid as a rock.

```
> terraform plan -out t.plan
newrelic_one_dashboard.exampledash: Refreshing state... [id=MjE5NDc1]

│ Error: Request cancelled
│ 
│   with provider["registry.terraform.io/hashicorp/aws"],
│   on provider.tf line 24, in provider "aws":
│   24: provider "aws" {
│ 
│ The plugin.(*GRPCProvider).GetProviderSchema request was cancelled.
```

Versions
```
> terraform version
Terraform v1.0.11
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.64.2
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/newrelic/newrelic v2.31.1
```

_ps. I'm running on a Apple M1_

**Comment by rdhar** [comment]
Thanks for the input, @pmoranga, that's not very promising to hear. Especially when it's occurring across different operating systems as well.

It looks like we have a similar source of issue as well: GRPCProvider. Curiously, last week saw the release of New Relic's .NET agent [v9.1.1](https://github.com/newrelic/newrelic-dotnet-agent/releases/tag/v9.1.1) which fixes an issue with gRPC libraries. This is the [issue](https://github.com/newrelic/newrelic-dotnet-agent/issues/781) and related pull requests [#782](https://github.com/newrelic/newrelic-dotnet-agent/pull/782) and [#788](https://github.com/newrelic/newrelic-dotnet-agent/pull/788).

Wonder if these recent changes are related in causing the ongoing issues. Wonder if any of those folks might have some idea: @JcolemanNR, @vuqtran88 and @jaffinito.

**Comment by JcolemanNR** [comment]
@rdhar, I do not believe these are related. Good hunting

**Comment by kidk** [comment]
I think your issue @JcolemanNR might be different from the one reported her. Could you create a ticket with debug output if the issue happens again? https://www.terraform.io/docs/internals/debugging.html

This seems related to alerting:

```

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0xa0 pc=0x12e7333]

goroutine 89 [running]:
github.com/newrelic/terraform-provider-newrelic/v2/newrelic.resourceNewRelicNrqlAlertConditionCreate(0x17bb9f8, 0xc0000d46c0, 0xc00013e480, 0x1421ae0, 0xc000281b30, 0xc000250970, 0xec1cb2, 0xc00013e280)
        /home/runner/work/terraform-provider-newrelic/terraform-provider-newrelic/newrelic/resource_newrelic_nrql_alert_condition.go:432 +0x7d3
```
https://github.com/newrelic/terraform-provider-newrelic/blob/main/newrelic/resource_newrelic_nrql_alert_condition.go#L432

**Comment by baNROne** [comment]
@rdhar Can you please re-submit or update, using the projects bug report issue template? If you create a new issue the template should populate automatically. You can also find the issue templates in the `.github` folder of the project.

**Comment by rdhar** [comment]
Since raising this ticket, I've sourced this issue down to this NRQL alert condition:

```sql
FROM Metric SELECT average(apm.service.datastore.operation.duration) FACET appName,table WHERE appName LIKE '%'
```

It appears that `apm.service.datastore.operation.duration` is causing oddities within certain alert conditions as well as dashboard widgets alike. As suggested, will re-submit a fresh issue/ticket template once I've scraped together something more concrete.
