### ISSUE TITLE
Drop rule with action drop_attributes_from_metric_aggregates got panic

### ISSUE THREAD

**Issue by zainul** [newrelic/terraform-provider-newrelic#1551]
Hi Newrelic team,

i trying using drop rule for action drop_attributes_from_metric_aggregates but i got panic and after check looks like the panic caused by un handled index of out range at this line terraform-provider-newrelic/newrelic/resource_newrelic_nrql_drop_rule.go:89

```
rule := created.Successes[0]
```

looks like there is missing response after terraform provider for drop rule call api, its actually success to plan but panic when applying

complete error

```
╷
│ Error: Plugin did not respond
│ 
│   with newrelic_nrql_drop_rule.sum-square-percentile["warehouse__warehouse_internal_token"],
│   on main.tf line 9, in resource "newrelic_nrql_drop_rule" "sum-square-percentile":
│    9: resource "newrelic_nrql_drop_rule" "sum-square-percentile" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵

Stack trace from the terraform-provider-newrelic_v2.33.0 plugin:

panic: runtime error: index out of range [0] with length 0

goroutine 41 [running]:
github.com/newrelic/terraform-provider-newrelic/v2/newrelic.resourceNewRelicNRQLDropRuleCreate(0x137f218, 0xc00068d620, 0xc000657b80, 0xfefc60, 0xc00068e0f0, 0xc000284420, 0xaa99ca, 0xc000657a00)
	/home/runner/work/terraform-provider-newrelic/terraform-provider-newrelic/newrelic/resource_newrelic_nrql_drop_rule.go:89 +0x66c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc0000b4e00, 0x137f1a8, 0xc0002e4980, 0xc000657b80, 0xfefc60, 0xc00068e0f0, 0x0, 0x0, 0x0)
	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.8.0/helper/schema/resource.go:330 +0x17f
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0000b4e00, 0x137f1a8, 0xc0002e4980, 0xc000667a00, 0xc000657a00, 0xfefc60, 0xc00068e0f0, 0x0, 0x0, 0x0, ...)
	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.8.0/helper/schema/resource.go:456 +0x67b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0000a47b0, 0x137f1a8, 0xc0002e4980, 0xc00063bf40, 0xc0002e4980, 0x110c820, 0xc00068f900)
	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.8.0/helper/schema/grpc_provider.go:977 +0xacf
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc000491640, 0x137f250, 0xc0002e4980, 0xc00065b6c0, 0xc000491640, 0xc00068f950, 0xc000619ba0)
	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.4.0/tfprotov5/tf5server/server.go:332 +0xb5
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x110c820, 0xc000491640, 0x137f250, 0xc00068f950, 0xc00068cfc0, 0x0, 0x137f250, 0xc00068f950, 0xc000158b40, 0x21b)
	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.4.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001f6c40, 0x13891d8, 0xc000293800, 0xc000314300, 0xc0000e5ec0, 0x199a3e0, 0x0, 0x0, 0x0)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc0001f6c40, 0x13891d8, 0xc000293800, 0xc000314300, 0x0)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0000a82b0, 0xc0001f6c40, 0x13891d8, 0xc000293800, 0xc000314300)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd

Error: The terraform-provider-newrelic_v2.33.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

time=2021-12-07T04:50:25+07:00 level=error msg=1 error occurred:
	* exit status 1

```

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

```
terraform-1.0.11 -v
Terraform v1.0.11
on linux_amd64
```

### Affected Resource(s)
Please list the resources as a list, for example:
- `newrelic_nrql_drop_rule`

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration

The **key** and **account id** already set in environment varibale
```hcl

  
terraform {
  required_providers {
    newrelic = {
      source  = "newrelic/newrelic"
    }
  }
}

resource "newrelic_nrql_drop_rule" "sum-square-percentile" {
  for_each = var.metrics
    description = format("filter drop rule cardinality")
    action = "drop_attributes_from_metric_aggregates"
    nrql = format("FROM Metric SELECT %s where metricName = '%s.mean.percentiles'" , join(",", var.attribute) , each.value)
}

```

### Actual Behavior
```
│ Error: Plugin did not respond
│ 
│   with newrelic_nrql_drop_rule.sum-square-percentile["warehouse__warehouse_internal_token"],
│   on main.tf line 9, in resource "newrelic_nrql_drop_rule" "sum-square-percentile":
│    9: resource "newrelic_nrql_drop_rule" "sum-square-percentile" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.

```

### Expected Behavior
applying success with return some id in output

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. create newrelic_nrql_drop_rule with action drop_attributes_from_metric_aggregates
2. `terraform apply`

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.
```
Stack trace from the terraform-provider-newrelic_v2.33.0 plugin:

panic: runtime error: index out of range [0] with length 0

goroutine 41 [running]:
github.com/newrelic/terraform-provider-newrelic/v2/newrelic.resourceNewRelicNRQLDropRuleCreate(0x137f218, 0xc00068d620, 0xc000657b80, 0xfefc60, 0xc00068e0f0, 0xc000284420, 0xaa99ca, 0xc000657a00)
	/home/runner/work/terraform-provider-newrelic/terraform-provider-newrelic/newrelic/resource_newrelic_nrql_drop_rule.go:89 +0x66c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc0000b4e00, 0x137f1a8, 0xc0002e4980, 0xc000657b80, 0xfefc60, 0xc00068e0f0, 0x0, 0x0, 0x0)
	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.8.0/helper/schema/resource.go:330 +0x17f
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0000b4e00, 0x137f1a8, 0xc0002e4980, 0xc000667a00, 0xc000657a00, 0xfefc60, 0xc00068e0f0, 0x0, 0x0, 0x0, ...)
	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.8.0/helper/schema/resource.go:456 +0x67b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0000a47b0, 0x137f1a8, 0xc0002e4980, 0xc00063bf40, 0xc0002e4980, 0x110c820, 0xc00068f900)
	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.8.0/helper/schema/grpc_provider.go:977 +0xacf
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc000491640, 0x137f250, 0xc0002e4980, 0xc00065b6c0, 0xc000491640, 0xc00068f950, 0xc000619ba0)
	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.4.0/tfprotov5/tf5server/server.go:332 +0xb5
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x110c820, 0xc000491640, 0x137f250, 0xc00068f950, 0xc00068cfc0, 0x0, 0x137f250, 0xc00068f950, 0xc000158b40, 0x21b)
	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.4.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001f6c40, 0x13891d8, 0xc000293800, 0xc000314300, 0xc0000e5ec0, 0x199a3e0, 0x0, 0x0, 0x0)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc0001f6c40, 0x13891d8, 0xc000293800, 0xc000314300, 0x0)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0000a82b0, 0xc0001f6c40, 0x13891d8, 0xc000293800, 0xc000314300)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd

Error: The terraform-provider-newrelic_v2.33.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

time=2021-12-07T04:50:25+07:00 level=error msg=1 error occurred:
	* exit status 1

```

**Comment by mbazhlekova** [comment]
Hi @zainul 👋  this feature is still in beta. Did you [request access](https://docs.newrelic.com/docs/data-apis/manage-data/drop-data-using-nerdgraph/#drop-attributes-on-dimensional-metric-rollups)?

**Comment by ganeshmuralidhar** [comment]
hello @mbazhlekova I already submitted the request on behalf of Zainul and added all accounts that would need this enabled. Can you please check?
