### ISSUE TITLE
interface conversion: interface {} is nil, not string | Alarm mute

### ISSUE THREAD

**Issue by xmariopereira** [newrelic/terraform-provider-newrelic#1597]
### Terraform Version
1.1.3 - Terraform
2.35.0 - NewRelic Provider

### Affected Resource(s)
newrelic_alert_muting_rule

### Terraform Configuration
```
resource "newrelic_alert_muting_rule" "apmAlarmsMuted" {
  name = "${var.environment}:apm_alarm_mute"
  count = length(var.core_name) > 0  ? 1 : 0
  enabled = true
  condition {
    conditions {
      attribute   = "tag.aws.logStream"
      operator    = "CONTAINS"
      values      = var.core_name
    }
    operator = "AND"
  }
}

resource "newrelic_alert_muting_rule" "infraAlarmsMuted" {
  name = "${var.environment}:infra_alarm_mute"
  count = length(var.terminal) > 0  ? 1 : 0
  enabled = true
  condition {
    conditions {
      attribute   = "tag.terminal"
      operator    = "CONTAINS"
      values      = var.terminal
    }
    operator = "AND"
  }
}

resource "newrelic_alert_muting_rule" "syntheticsAlarmsMuted" {
  name = "${var.environment}:synthetics_alarm_mute"
  count = length(var.syntheticsName) > 0 ? 1 : 0
  enabled = true
  condition {
    conditions {
      attribute   = "targetName"
      operator    = "CONTAINS"
      values      = var.syntheticsName
    }
    operator = "AND"
  }
}
```

```
variable "environment" {
  type = string
}

variable "core_name" {
  type = list(string)
  default = [""]
}

variable "terminal" {
  type = list(string)
  default = [""]
}

variable "syntheticsName" {
  type = list(string)
  default = [""]
}
```
### Actual Behavior
```
module.alarm_muting.newrelic_alert_muting_rule.infraAlarmsMuted[0]: Creating...
module.alarm_muting.newrelic_alert_muting_rule.syntheticsAlarmsMuted[0]: Creating...
module.alarm_muting.newrelic_alert_muting_rule.apmAlarmsMuted[0]: Creating...
╷
│ Error: Plugin did not respond
│ 
│   with module.alarm_muting.newrelic_alert_muting_rule.apmAlarmsMuted[0],
│   on modules/alarm_muting/main.tf line 1, in resource "newrelic_alert_muting_rule" "apmAlarmsMuted":
│    1: resource "newrelic_alert_muting_rule" "apmAlarmsMuted" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with module.alarm_muting.newrelic_alert_muting_rule.infraAlarmsMuted[0],
│   on modules/alarm_muting/main.tf line 15, in resource "newrelic_alert_muting_rule" "infraAlarmsMuted":
│   15: resource "newrelic_alert_muting_rule" "infraAlarmsMuted" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with module.alarm_muting.newrelic_alert_muting_rule.syntheticsAlarmsMuted[0],
│   on modules/alarm_muting/main.tf line 29, in resource "newrelic_alert_muting_rule" "syntheticsAlarmsMuted":
│   29: resource "newrelic_alert_muting_rule" "syntheticsAlarmsMuted" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵
Stack trace from the terraform-provider-newrelic_v2.35.0 plugin:
panic: interface conversion: interface {} is nil, not string
goroutine 12 [running]:
github.com/newrelic/terraform-provider-newrelic/v2/newrelic.expandMutingRuleValues(0xc000600570, 0x1, 0x1, 0x6, 0xc00060a0a8, 0x1)
	/home/runner/work/terraform-provider-newrelic/terraform-provider-newrelic/newrelic/structures_newrelic_alert_muting_rule.go:259 +0xe5
github.com/newrelic/terraform-provider-newrelic/v2/newrelic.expandMutingRuleCondition(0x101c800, 0xc00058c9f0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/runner/work/terraform-provider-newrelic/terraform-provider-newrelic/newrelic/structures_newrelic_alert_muting_rule.go:249 +0x1af
github.com/newrelic/terraform-provider-newrelic/v2/newrelic.expandMutingRuleConditionGroup(0xc00058c990, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/runner/work/terraform-provider-newrelic/terraform-provider-newrelic/newrelic/structures_newrelic_alert_muting_rule.go:224 +0x125
github.com/newrelic/terraform-provider-newrelic/v2/newrelic.expandMutingRuleCreateInput(0xc000097800, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/runner/work/terraform-provider-newrelic/terraform-provider-newrelic/newrelic/structures_newrelic_alert_muting_rule.go:20 +0x252
github.com/newrelic/terraform-provider-newrelic/v2/newrelic.resourceNewRelicAlertMutingRuleCreate(0x139b878, 0xc000582a80, 0xc000097800, 0x1006160, 0xc0002043c0, 0xc000600330, 0xaa9fca, 0xc000097680)
	/home/runner/work/terraform-provider-newrelic/terraform-provider-newrelic/newrelic/resource_newrelic_alert_muting_rule.go:189 +0xa5
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc00027f6c0, 0x139b808, 0xc000340b00, 0xc000097800, 0x1006160, 0xc0002043c0, 0x0, 0x0, 0x0)
	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.9.0/helper/schema/resource.go:341 +0x17f
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc00027f6c0, 0x139b808, 0xc000340b00, 0xc000398b60, 0xc000097680, 0x1006160, 0xc0002043c0, 0x0, 0x0, 0x0, ...)
	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.9.0/helper/schema/resource.go:467 +0x67b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00000c0c0, 0x139b808, 0xc000340b00, 0xc0003c0370, 0xc000340b00, 0x1125f60, 0xc0003e2300)
	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.9.0/helper/schema/grpc_provider.go:977 +0xacf
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0002fe1c0, 0x139b8b0, 0xc000340b00, 0xc0003601c0, 0xc0002fe1c0, 0xc0003e23f0, 0xc0001b1ba0)
	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.4.0/tfprotov5/tf5server/server.go:332 +0xb5
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x1125f60, 0xc0002fe1c0, 0x139b8b0, 0xc0003e23f0, 0xc0002b3c20, 0x0, 0x139b8b0, 0xc0003e23f0, 0xc000050380, 0x1b0)
	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.4.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000424540, 0x13a5898, 0xc000131680, 0xc00058f100, 0xc000094540, 0x19c2560, 0x0, 0x0, 0x0)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc000424540, 0x13a5898, 0xc000131680, 0xc00058f100, 0x0)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0000483e0, 0xc000424540, 0x13a5898, 0xc000131680, 0xc00058f100)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd
Error: The terraform-provider-newrelic_v2.35.0 plugin crashed!
This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Expected Behavior
Creation of Alarm muting rules

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by emetcalf9** [comment]
Can you confirm that you are passing in actual values to "core_name", "terminal", and "syntheticsName"? I get the same error when I use your exact config from the issue here, but if I add a non-empty string the Muting Rule is created successfully.

**Comment by xmariopereira** [comment]
@emetcalf9 

```
  + resource "newrelic_alert_muting_rule" "apmAlarmsMuted" {
      + account_id = (known after apply)
      + enabled    = true
      + id         = (known after apply)
      + name       = "mario_pereira:apm_alarm_mute"
      + condition {
          + operator = "AND"
          + conditions {
              + attribute = "tag.aws.logStream"
              + operator  = "CONTAINS"
              + values    = [
                  + "",
                ]
            }
        }
    }
  # module.alarm_muting.newrelic_alert_muting_rule.infraAlarmsMuted[0] will be created
  + resource "newrelic_alert_muting_rule" "infraAlarmsMuted" {
      + account_id = (known after apply)
      + enabled    = true
      + id         = (known after apply)
      + name       = "mario_pereira:infra_alarm_mute"
      + condition {
          + operator = "AND"
          + conditions {
              + attribute = "tag.terminal"
              + operator  = "CONTAINS"
              + values    = [
                  + "",
                ]
            }
        }
    }
  # module.alarm_muting.newrelic_alert_muting_rule.syntheticsAlarmsMuted[0] will be created
  + resource "newrelic_alert_muting_rule" "syntheticsAlarmsMuted" {
      + account_id = (known after apply)
      + enabled    = true
      + id         = (known after apply)
      + name       = "mario_pereira:synthetics_alarm_mute"
      + condition {
          + operator = "AND"
          + conditions {
              + attribute = "targetName"
              + operator  = "CONTAINS"
              + values    = [
                  + "",
                ]
            }
        }
    }
```

**Comment by xmariopereira** [comment]
@emetcalf9 the thing is that I only want to mute if there are values inside. 

that is why i ```use count = length(var.terminal) > 0  ? 1 : 0```

**Comment by xmariopereira** [comment]
Gonna close this issue. Found my problem... needs to be like this

```
  default = []
  nullable = true
``` 

removed the '' works fine.
