### ISSUE TITLE
Bug: Saving an alert policy in the UI with a since_value causes the plugin to crash

### ISSUE THREAD

**Issue by EddieEldridge** [newrelic/terraform-provider-newrelic#1599]
### Terraform Version
Terraform Version: 1.0.4

### Provider Version
terraform-provider-newrelic: 2.35.0

### Affected Resource(s)
- newrelic_nrql_alert_condition

## Example Config that throws the error
```
resource "newrelic_alert_policy" "policy_0" {
  name                = "test (Policy)"
  account_id          =  REDACTED
  incident_preference = "PER_CONDITION_AND_TARGET"
}

resource "newrelic_nrql_alert_condition" "policy_0_condition_0" {
  account_id                     = REDACTED
  policy_id                      = newrelic_alert_policy.policy_0.id
  type                           = "static"
  name                           = "Test name"
  description                    = "Test desc"
  runbook_url                    = "REDACTED"
  enabled                        = true
  violation_time_limit_seconds   = 86400
  value_function                 = "sum"
  expiration_duration            = 120
  close_violations_on_expiration = true

  nrql {
    query       = <<-EOT
        SELECT count(*) FROM TestEvent WHERE eventTag = 'error' AND awsRegion = 'us-east-1' AND  errorType = 'HTTPError' AND statusCode = 404
    EOT
    since_value = 1
  }
  critical {
    operator           = "above"
    threshold          = 50
    threshold_duration = 300
    time_function      = "any"
  }
  warning {
    operator           = "above"
    threshold          = 10
    threshold_duration = 300
    time_function      = "any"
  }
}
```

### Actual Behavior
- The plugin crashes when running ```terraform apply```

### Expected Behavior
- The plugin to not crash

### Steps to Reproduce
1. Define a NewRelic alert policy (see above) in Terraform with a since_value
2. Run ```terraform apply```
3. Open the alert policy in the UI
4. Modify the window duration to anything and click '**Use event flow**'
![image](https://user-images.githubusercontent.com/22448079/150556477-beb1ddd1-6a28-40be-8d79-be4c89c6a516.png)
5. Click '**Save condition**'
6. Run ```terraform apply```
7. Plugin crashes 

### Panic Output
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1ae1411]

goroutine 116 [running]:
github.com/newrelic/terraform-provider-newrelic/v2/newrelic.flattenNrql(0xc0007cc3c0, 0x92, 0x0, 0xc0009b4b70, 0xc0009b4b70, 0x1, 0x0)
        /home/runner/work/terraform-provider-newrelic/terraform-provider-newrelic/newrelic/structures_newrelic_nrql_alert_condition.go:700 +0x1d1
github.com/newrelic/terraform-provider-newrelic/v2/newrelic.flattenNrqlAlertCondition(0xd31d0, 0xc0003f8000, 0xc000315980, 0xd31d0, 0xc0004220c0)
        /home/runner/work/terraform-provider-newrelic/terraform-provider-newrelic/newrelic/structures_newrelic_nrql_alert_condition.go:572 +0x3d5
github.com/newrelic/terraform-provider-newrelic/v2/newrelic.resourceNewRelicNrqlAlertConditionRead(0x1f7d698, 0xc0004f7680, 0xc000315980, 0x1bed8e0, 0xc0007bbcb0, 0xc000625960, 0xc000379908, 0x100df38)
        /home/runner/work/terraform-provider-newrelic/terraform-provider-newrelic/newrelic/resource_newrelic_nrql_alert_condition.go:465 +0x487
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc00011cd20, 0x1f7d628, 0xc00010fb80, 0xc000315980, 0x1bed8e0, 0xc0007bbcb0, 0x0, 0x0, 0x0)
        /home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.8.0/helper/schema/resource.go:347 +0x17f
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc00011cd20, 0x1f7d628, 0xc00010fb80, 0xc000011c70, 0x1bed8e0, 0xc0007bbcb0, 0xc00000ebe0, 0x0, 0x0, 0x0)
        /home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.8.0/helper/schema/resource.go:624 +0x1cb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc0000bc3a8, 0x1f7d628, 0xc00010fb80, 0xc00010fbc0, 0xc00010fb80, 0x100b665, 0x1cc6060)
        /home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.8.0/helper/schema/grpc_provider.go:576 +0x47d
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc000308420, 0x1f7d6d0, 0xc00010fb80, 0xc0004f7140, 0xc000308420, 0xc000500180, 0xc00052bba0)
        /home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.4.0/tfprotov5/tf5server/server.go:298 +0x105
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0x1d0aaa0, 0xc000308420, 0x1f7d6d0, 0xc000500180, 0xc0004f70e0, 0x0, 0x1f7d6d0, 0xc000500180, 0xc000508900, 0x44b)
        /home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.4.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000242c40, 0x1f877f8, 0xc000602f00, 0xc000298100, 0xc000980510, 0x259b570, 0x0, 0x0, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc000242c40, 0x1f877f8, 0xc000602f00, 0xc000298100, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0003101b0, 0xc000242c40, 0x1f877f8, 0xc000602f00, 0xc000298100)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd
```

### Important Factoids
- When inspecting the state file, it looks as if ```evaluation_offset``` is being set to ```0``` for our alert policy

```
"nrql": [
              {
                "evaluation_offset": 0,
                "query": "  SELECT count(*) FROM TestEvent WHERE eventTag = 'error' AND awsRegion = 'us-east-1' AND  errorType = 'HTTPError' AND statusCode = 404\n",
                "since_value": "1"
              }
            ],
```

**Comment by kidk** [comment]
Thanks @EddieEldridge We'll take a look.
