### ISSUE TITLE
Can't create Workflow with email channel - INVALID_PARAMETER: A channel with id was not found

### ISSUE THREAD

**Issue by gutsul** [newrelic/terraform-provider-newrelic#1974]
### Terraform Version
```
╰─ $ terraform -v
Terraform v1.2.8
on linux_amd64
+ provider registry.terraform.io/newrelic/newrelic v3.0.3
```
### Affected Resource(s)
- `newrelic_workflow`

### Terraform Configuration
Please include your provider configuration (sensitive details redacted) as well as the configuration of the resources and/or data sources related to the bug report.
```
terraform {
  required_providers {
    newrelic = {
      source = "newrelic/newrelic"
      version = "3.0.3"
    }
  }
}

provider "newrelic" {
  # Configuration options
  account_id = "IDGOESHERE"
  api_key = "APIKEYGOESHERE"
  region = "US"
}

resource "newrelic_notification_destination" "email" {
  account_id = var.account_id
  name = "email-devops-team"
  type = "EMAIL"

  property {
    key = "email"
    value = ["example@gmail.com"]


  # https://github.com/newrelic/terraform-provider-newrelic/issues/1939
  auth_basic {
    user     = "username"
    password = "password"
  }
}

resource "newrelic_notification_channel" "email_channel" {
  account_id = var.account_id
  name = "email-devops-team"
  type = "EMAIL"
  destination_id = newrelic_notification_destination.email.id
  product = "ERROR_TRACKING"

  property {
    key = "subject"
    value = "New Subject Title"
  }
}


resource "newrelic_workflow" "tf_workflow" {
  name = "tf-workflow"
  account_id = var.account_id
  muting_rules_handling = "NOTIFY_ALL_ISSUES"
  workflow_enabled = false

  enrichments {
    nrql {
      name = "Log count"
      configurations {
       query = "SELECT count(*) FROM Log"
      }
    }
  }

  issues_filter {
    name = "Filter-name"
    type = "FILTER"

    predicates {
      attribute = "accumulations.sources"
      operator = "EXACTLY_MATCHES"
      values = [ "newrelic" ]
    }
  }

  destination_configuration {
    channel_id = newrelic_notification_channel.email_channel.id
  }
}

```
### Actual Behavior
The Workflow is not created.
```
Error: INVALID_PARAMETER: A channel with id was not found
```

### Expected Behavior
The Workflow is created.

### Steps to Reproduce
Generate the configuration for a new workflow.
``` 
terraform apply
```
See error message.

**Comment by n-s-s-p-k** [comment]
Hi @gutsul, thanks for raising the issue. We will prioritize the issue.

**Comment by eniayomi** [comment]
Hello, please is there a timeline to when this will be resolved?

**Comment by NSSPKrishna** [comment]
Hi @eniayomi, looks like the issue is with the api. Notified the concerned team about the issue.

**Comment by louhnmn** [comment]
having the same issue with `INVALID PARAMETER: A channel ... was not found`. But with a webhook not email.
Also if I apply another time after that `INVALID...`-error message the whole newrelic plugin crashes:

```
╷
│ Error: Plugin did not respond
│ 
│   with newrelic_notification_channel.google_chat_channel,
│   on alerts.tf line 12, in resource "newrelic_notification_channel" "google_chat_channel":
│   12: resource "newrelic_notification_channel" "google_chat_channel" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Request cancelled
│ 
│   with newrelic_alert_policy.ssl_certificates,
│   on alerts.tf line 82, in resource "newrelic_alert_policy" "ssl_certificates":
│   82: resource "newrelic_alert_policy" "ssl_certificates" {
│ 
│ The plugin.(*GRPCProvider).ReadResource request was cancelled.
╵

Stack trace from the terraform-provider-newrelic_v3.1.0 plugin:

panic: runtime error: index out of range [0] with length 0

goroutine 116 [running]:
github.com/newrelic/terraform-provider-newrelic/v2/newrelic.resourceNewRelicNotificationChannelRead({0x1c09290, 0xc000688ae0}, 0xc0001f6f80, {0x193f180?, 0xc0007bc4e0})
        /home/runner/work/terraform-provider-newrelic/terraform-provider-newrelic/newrelic/resource_newrelic_notifications_channel.go:132 +0x44e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc0004aafc0, {0x1c092c8, 0xc000401830}, 0xd?, {0x193f180, 0xc0007bc4e0})
        /home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.20.0/helper/schema/resource.go:724 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0004aafc0, {0x1c092c8, 0xc000401830}, 0xc0001244e0, {0x193f180, 0xc0007bc4e0})
        /home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.20.0/helper/schema/resource.go:1015 +0x585
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc000133cf8, {0x1c092c8?, 0xc000401710?}, 0xc000257e80)
        /home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.20.0/helper/schema/grpc_provider.go:613 +0x497
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc0002661e0, {0x1c092c8?, 0xc000401140?}, 0xc000688840)
        /home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.12.0/tfprotov5/tf5server/server.go:747 +0x41e
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x1a390e0?, 0xc0002661e0}, {0x1c092c8, 0xc000401140}, 0xc000354540, 0x0)
        /home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.12.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001ea1e0, {0x1c0cbd0, 0xc0003ceb60}, 0xc0005b4000, 0xc0004bb2f0, 0x21d04f0, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.48.0/server.go:1295 +0xb0b
google.golang.org/grpc.(*Server).handleStream(0xc0001ea1e0, {0x1c0cbd0, 0xc0003ceb60}, 0xc0005b4000, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.48.0/server.go:1636 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.48.0/server.go:932 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.48.0/server.go:930 +0x28a

Error: The terraform-provider-newrelic_v3.1.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

After that I have to delete the channel state with `terraform state rm newrelic_notification_channel.google_chat_channel` to make things work again.

**Comment by NSSPKrishna** [comment]
Hi @gutsul to create a workflow using email kindly change `product = "ERROR_TRACKING"` to `product = "IINT"`

**Comment by NSSPKrishna** [comment]
Hi @louhnmn, thanks for raising the issue. Can please raise a new issue?

**Comment by gutsul** [comment]
@n-s-s-p-k It`s works. I have created workflow using your advice.

**Comment by jpperdon** [comment]
Hello,

What was the fix on this?
