### ISSUE TITLE
newrelic_synthetics_script_monitor reports server error when setting runtime

### ISSUE THREAD

**Issue by megaloni** [newrelic/terraform-provider-newrelic#2022]
### Terraform Version
Terraform v1.2.4

### Affected Resource(s)
- `newrelic_synthetics_script_monitor`

### Terraform Configuration
```hcl
terraform {
  required_version = ">= 1.0.0"

  required_providers {
    newrelic = {
      source = "newrelic/newrelic"
      version = "3.2.1"
    }
  }
}

resource "newrelic_synthetics_script_monitor" "browser_script_synthetics_scripts" {
  name = "my-test-terraform-synthetic"
  type = "SCRIPT_BROWSER"
  period = "EVERY_10_MINUTES"
  status = "ENABLED"
  locations_public = ["US_EAST_1"]

  enable_screenshot_on_failure_and_script = false
  script = "$browser.get('https://www.google.com')"
}
```

### Actual Behavior
```
13:27:53  Error: Plugin did not respond
13:27:53  
13:27:53    with newrelic_synthetics_script_monitor.browser_script_synthetics_scripts["insights_ping_synthetic"],
13:27:53    on synthetics.tf line 1, in resource "newrelic_synthetics_script_monitor" "browser_script_synthetics_scripts":
13:27:53     1: resource "newrelic_synthetics_script_monitor" "browser_script_synthetics_scripts" {
13:27:53  
13:27:53  The plugin encountered an error, and failed to respond to the
13:27:53  plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain
13:27:53  more details.
13:27:53  
13:27:53  Stack trace from the terraform-provider-newrelic_v3.2.1 plugin:
13:27:53  
13:27:53  panic: runtime error: invalid memory address or nil pointer dereference
13:27:53  [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xc3cc3e]
13:27:53  
13:27:53  goroutine 15 [running]:
13:27:53  github.com/newrelic/terraform-provider-newrelic/v2/newrelic.resourceNewRelicSyntheticsScriptMonitorCreate({0x100fef0, 0xc0002fa5a0}, 0x0?, {0xd44d80?, 0xc00086a3c0?})
13:27:53  	/home/runner/work/terraform-provider-newrelic/terraform-provider-newrelic/newrelic/resource_newrelic_synthetics_script_monitor.go:150 +0x51e
13:27:53  github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc00049cfc0, {0x100ff28, 0xc00086bb30}, 0xd?, {0xd44d80, 0xc00086a3c0})
13:27:53  	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.20.0/helper/schema/resource.go:707 +0x12e
13:27:53  github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc00049cfc0, {0x100ff28, 0xc00086bb30}, 0xc0002bf110, 0xc0004f4e80, {0xd44d80, 0xc00086a3c0})
13:27:53  	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.20.0/helper/schema/resource.go:837 +0xa7a
13:27:53  github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000129998, {0x100ff28?, 0xc00086ba10?}, 0xc0004345f0)
13:27:53  	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.20.0/helper/schema/grpc_provider.go:1021 +0xe3c
13:27:53  github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0003f9220, {0x100ff28?, 0xc00086b3e0?}, 0xc0004101c0)
13:27:53  	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.12.0/tfprotov5/tf5server/server.go:813 +0x4fc
13:27:53  github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xe3e1c0?, 0xc0003f9220}, {0x100ff28, 0xc00086b3e0}, 0xc000410150, 0x0)
13:27:53  	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.12.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
13:27:53  google.golang.org/grpc.(*Server).processUnaryRPC(0xc00043a000, {0x10137b0, 0xc000582340}, 0xc0004ec240, 0xc0004acdb0, 0x15d43c0, 0x0)
13:27:53  	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.48.0/server.go:1295 +0xb0b
13:27:53  google.golang.org/grpc.(*Server).handleStream(0xc00043a000, {0x10137b0, 0xc000582340}, 0xc0004ec240, 0x0)
13:27:53  	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.48.0/server.go:1636 +0xa1b
13:27:53  google.golang.org/grpc.(*Server).serveStreams.func1.2()
13:27:53  	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.48.0/server.go:932 +0x98
13:27:53  created by google.golang.org/grpc.(*Server).serveStreams.func1
13:27:53  	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.48.0/server.go:930 +0x28a
13:27:53  
13:27:53  Error: The terraform-provider-newrelic_v3.2.1 plugin crashed!
13:27:53  
13:27:53  This is always indicative of a bug within the plugin. It would be immensely
13:27:53  helpful if you could report the crash with the plugin's maintainers so that it
13:27:53  can be fixed. The output above should help diagnose the issue.
```

### Expected Behavior
Synthetic resource created successfully.

### Steps to Reproduce
1. `terraform plan`
2. `terraform apply`

### Debug Output
https://gist.github.com/megaloni/2b7ca7cc5a99bbd8c819036805b8466c

### Panic Output
https://gist.github.com/megaloni/2b7ca7cc5a99bbd8c819036805b8466c

### Important Factoids
Nothing atypical about our accounts. This also happens using nerdgraph through GraphiQL website directly:

Request:
```
mutation {
  syntheticsCreateScriptBrowserMonitor(accountId: <REDACTED>, monitor: {
    locations: {public: ["US_EAST_1"]}, 
    name: "mesmith-test-synthetic", 
    period: EVERY_10_MINUTES, 
    script: "$browser.get('https://www.google.com')", 
    status: ENABLED, 
    runtime: {runtimeType: "CHROME_BROWSER", runtimeTypeVersion: "100"}}) {
    errors {
      description
      type
    }
  }
}
```

Response:
```
{
  "data": {
    "syntheticsCreateScriptBrowserMonitor": null
  },
  "errors": [
    {
      "extensions": {
        "classification": "DataFetchingException",
        "errorClass": "SERVER_ERROR"
      },
      "locations": [
        {
          "column": 3,
          "line": 2
        }
      ],
      "message": "Exception while fetching data (/createScriptBrowserMonitor) : null",
      "path": [
        "syntheticsCreateScriptBrowserMonitor"
      ]
    }
  ]
}
```

### References
Not that I know of.

**Comment by mbazhlekova** [comment]
Hi @megaloni 👋 I'm not able to reproduce this issue with the Terraform config you provided. Are you still seeing it happen on the latest version of the TF Provider?

**Comment by NSSPKrishna** [comment]
Hi @megaloni, We haven’t heard back from you in a long time so we will close the ticket. If you feel this is still a valid request or bug, feel free to create a new issue.
