### ISSUE TITLE
The terraform-provider-newrelic_v3.5.2 plugin crashed!

### ISSUE THREAD

**Issue by Joshua-Benfell** [newrelic/terraform-provider-newrelic#2116]
Deleted a workflow created with terraform through the New Relic Workflows UI then attempted to rerun terraform

## Please include the following with your bug report

> :warning: **Important:** Failure to include the following, such as omitting the Terraform configuration in question, may delay resolving the issue.

- [x] Your New Relic `provider` [configuration](#terraform-configuration-files) (sensitive details redacted)
- [x] A list of [affected resources](#affected-resources) and/or data sources
- [x] The [configuration](#terraform-configuration-files) of the resources and/or data sources related to the bug report (i.e. from the list mentioned above)
- [x] Description of the [current behavior](#actual-behavior) (the bug)
- [x] Description of the [expected behavior](#expected-behavior)
- [x] Any related [log output](#debug-output)

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.
```Bash
terraform -v                                                                                
Terraform v1.3.4
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.5.0
+ provider registry.terraform.io/newrelic/newrelic v3.5.2
```

### Affected Resource(s)
Please list the resources as a list, for example:
- `newrelic_workflow`
- `newrelic_alert_policy_channel`

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration
> Please include your `provider` configuration (sensitive details redacted) as well as the configuration of the resources and/or data sources related to the bug report.
```hcl
terraform {
  required_providers {
    # Docs https://registry.terraform.io/providers/hashicorp/aws/latest/docs
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.5.0"
    }

    # Docs https://registry.terraform.io/providers/newrelic/newrelic/latest/docs
    newrelic = {
      source  = "newrelic/newrelic"
      version = "~> 3.5.1"
    }
  }
}
```

### Actual Behavior
The plugin crashed on the alert policy channel and workflows resources.
We tried upgrading to 3.6.1 and it also crashed in the same fashion with the same error.

### Expected Behavior
What should have happened?
Should have recreated the workflow that was deleted
Shouldn't have effected the alert policy channels

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.
```
Stack trace from the terraform-provider-newrelic_v3.5.2 plugin:

panic: runtime error: index out of range [0] with length 0

goroutine 2882 [running]:
github.com/newrelic/terraform-provider-newrelic/v2/newrelic.resourceNewRelicWorkflowRead({0x1c0cb10, 0xc00087e480}, 0xc000391580, {0x18e4160?, 0xc0004a1c50})
	/home/runner/work/terraform-provider-newrelic/terraform-provider-newrelic/newrelic/resource_newrelic_workflow.go:487 +0x3cd
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc00051aa80, {0x1c0cb48, 0xc001724ba0}, 0xd?, {0x18e4160, 0xc0004a1c50})
	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.20.0/helper/schema/resource.go:724 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc00051aa80, {0x1c0cb48, 0xc001724ba0}, 0xc0005236c0, {0x18e4160, 0xc0004a1c50})
	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.20.0/helper/schema/resource.go:1015 +0x585
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00012f980, {0x1c0cb48?, 0xc001724a80?}, 0xc0006dc240)
	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.20.0/helper/schema/grpc_provider.go:613 +0x497
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc000475220, {0x1c0cb48?, 0xc001724390?}, 0xc00087e060)
	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.12.0/tfprotov5/tf5server/server.go:747 +0x41e
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x1a3bd00?, 0xc000475220}, {0x1c0cb48, 0xc001724390}, 0xc000398000, 0x0)
	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.12.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0004a6000, {0x1c10450, 0xc0000036c0}, 0xc0005ce000, 0xc000518f30, 0x21d8510, 0x0)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.48.0/server.go:1295 +0xb0b
google.golang.org/grpc.(*Server).handleStream(0xc0004a6000, {0x1c10450, 0xc0000036c0}, 0xc0005ce000, 0x0)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.48.0/server.go:1636 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.48.0/server.go:932 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.48.0/server.go:930 +0x28a

Error: The terraform-provider-newrelic_v3.5.2 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

Terraform state is in an S3 bucket

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:

**Comment by IliaShurygin** [comment]
Hi! Thank you for the report!
I believe @sanderblue has fixed this crash a couple of days ago in https://github.com/newrelic/terraform-provider-newrelic/pull/2130.
The fix has been released in [v3.8.0](https://github.com/newrelic/terraform-provider-newrelic/releases/tag/v3.8.0) yesterday
