### ISSUE TITLE
Error: rpc error: code = Unavailable desc = transport is closing

### ISSUE THREAD

**Issue by OllyNural** [newrelic/terraform-provider-newrelic#888]
Hi all,

### Terraform Version
**version**: 0.12.11

Unable to upgrade currently

### Affected Resource(s)
- newrelic_alert_channel

### Terraform Configuration Files
I can't post much Terraform but I've stripped down a bit.
https://gist.github.com/OllyNural/7b1276f08b3d5364c19a3bae2e31d329

### Debug Output
No errors when running terraform plan

```
$ terraform apply .xxx.terraform.plan.tfout
newrelic_nrql_alert_condition.sdapi_not_authorised: Modifying... [id=xxx:XXX]
newrelic_nrql_alert_condition.sdapi_hard_limit_breached: Modifying... [id=xxx:XXX]
newrelic_nrql_alert_condition.sdapi_usage_exceeded: Modifying... [id=xxx:XXX]
newrelic_alert_channel.main: Creating...

Error: rpc error: code = Unavailable desc = transport is closing

Error: rpc error: code = Unavailable desc = transport is closing

Error: rpc error: code = Unavailable desc = transport is closing

Error: rpc error: code = Unavailable desc = transport is closing

panic: interface conversion: interface {} is nil, not map[string]interface {}
2020-09-16T16:19:01.518Z [DEBUG] plugin.terraform-provider-newrelic_v1.16.0_x4: 
2020-09-16T16:19:01.518Z [DEBUG] plugin.terraform-provider-newrelic_v1.16.0_x4: goroutine 67 [running]:
2020-09-16T16:19:01.518Z [DEBUG] plugin.terraform-provider-newrelic_v1.16.0_x4: github.com/terraform-providers/terraform-provider-newrelic/newrelic.expandAlertChannel(0xc0002e4c40, 0x400000000000000, 0xffffffffffffffff, 0x412c12)
2020-09-16T16:19:01.518Z [DEBUG] plugin.terraform-provider-newrelic_v1.16.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-newrelic/newrelic/structures_newrelic_alert_channel.go:26 +0x543
2020-09-16T16:19:01.518Z [DEBUG] plugin.terraform-provider-newrelic_v1.16.0_x4: github.com/terraform-providers/terraform-provider-newrelic/newrelic.resourceNewRelicAlertChannelCreate(0xc0002e4c40, 0xe5cda0, 0xc00063fd60, 0x2, 0x1a18200)
2020-09-16T16:19:01.518Z [DEBUG] plugin.terraform-provider-newrelic_v1.16.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-newrelic/newrelic/resource_newrelic_alert_channel.go:260 +0x6e
2020-09-16T16:19:01.518Z [DEBUG] plugin.terraform-provider-newrelic_v1.16.0_x4: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc00015ee80, 0xc0000e32c0, 0xc000284740, 0xe5cda0, 0xc00063fd60, 0xc0005e9101, 0xc00013e840, 0xc0005e9198)
2020-09-16T16:19:01.518Z [DEBUG] plugin.terraform-provider-newrelic_v1.16.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-newrelic/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/resource.go:305 +0x365

```

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

I'm unable to run it locally at the moment, only on CI. I can run this tomorrow morning to add this.

### Expected Behavior
What should have happened?

Successfully runs terraform apply.

### Actual Behavior
What actually happened?

Errors with the above error.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan -out=.xxx.terraform.plan.tfout -var-file=terraform.tfvars`
2. `terraform apply .xxx.terraform.plan.tfout`

### Important Factoids
N/A

### References
- https://github.com/terraform-providers/terraform-provider-github/issues/284
- https://github.com/hashicorp/terraform/issues/23088
- https://github.com/terraform-providers/terraform-provider-aws/issues/11420

**Comment by sanderblue** [comment]
@OllyNural, thanks for reporting! Per your comment in your [gist](https://gist.github.com/OllyNural/7b1276f08b3d5364c19a3bae2e31d329), I was able to confirm the error is due to the [`service_key`](https://gist.github.com/OllyNural/7b1276f08b3d5364c19a3bae2e31d329#file-pagerduty-tf-L37) being empty. 

I don't see `module.pagerduty_base.newrelic_integration_key` defined in your module, but maybe it's defined in the remote `source` module defined [here](https://gist.github.com/OllyNural/7b1276f08b3d5364c19a3bae2e31d329#file-pagerduty-tf-L13). If you're using a variable for that value in your `.tfvars` file, please double check that you set it.

Even if it is defined in your remote "parent" module and in your `.tfvars`, for a bit more precise debugging, I would try using a more direct approach by referencing the key via a local variable you set within the gist's configuration.

```
# Use a local variable to debug and confirm
locals {
  newrelic_integration_key = "Put your key here"
}

resource "newrelic_alert_channel" "main" {
  name = "${var.service_name}-newrelic"
  type = "pagerduty"

  config {
    # Use a local variable to confirm
    service_key ="${local.newrelic_integration_key}"
  }
}
```

**Comment by c-carpenter** [comment]
I had this problem. It was due to not having updated my environment variable to the v2.x format.

**Comment by sanderblue** [comment]
Closing due inactivity and a fix was provided above 🙂
